-- AddForeignKey
ALTER TABLE "App" ADD CONSTRAINT "App_id_fkey" FOREIGN KEY ("id") REFERENCES "AppUrl"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AppToApp" ADD CONSTRAINT "AppToApp_leftId_fkey" FOREIGN KEY ("leftId") REFERENCES "App"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AppToApp" ADD CONSTRAINT "AppToApp_rightId_fkey" FOREIGN KEY ("rightId") REFERENCES "App"("id") ON DELETE CASCADE ON UPDATE CASCADE;
